#!/usr/bin/env bash
#
# Panel installation and configuration
#

[[ -n "${_PANEL_SH_LOADED:-}" ]] && return 0
readonly _PANEL_SH_LOADED=1

# =============================================================================
# Panel Installation
# =============================================================================

install_panel() {
    log_step "Installing Lumo Panel"

    if [[ -d "$INSTALL_DIR" ]]; then
        log_warning "Installation directory exists: $INSTALL_DIR"
        if confirm "Remove and reinstall?" "n"; then
            rm -rf "$INSTALL_DIR"
        else
            log_info "Keeping existing installation"
            return 0
        fi
    fi

    mkdir -p "$INSTALL_DIR"
    add_cleanup_task "rm -rf $INSTALL_DIR"

    log_info "Cloning Lumo Panel repository..."

    if git clone --depth 1 --branch "$LUMO_VERSION" https://github.com/lumopanel/panel.git "$INSTALL_DIR" 2>/dev/null; then
        log_success "Panel repository cloned"
    else
        log_warning "Could not clone repository. Creating directory structure for manual installation..."
        mkdir -p "$INSTALL_DIR"/{storage/{app/public,framework/{cache/data,sessions,views},logs},bootstrap/cache,public,database}

        if [[ ! -f "$INSTALL_DIR/composer.json" ]]; then
            cat > "$INSTALL_DIR/composer.json" << 'EOF'
{
    "name": "lumopanel/panel",
    "type": "project",
    "require": {
        "php": "^8.2"
    }
}
EOF
        fi
    fi

    # Set ownership to lumo user
    chown -R "${LUMO_USER}:${LUMO_GROUP}" "$INSTALL_DIR"
    chmod -R 755 "$INSTALL_DIR"
    chmod -R 775 "$INSTALL_DIR/storage" "$INSTALL_DIR/bootstrap/cache" 2>/dev/null || true

    # Create tmp directory for uploads
    mkdir -p "${INSTALL_DIR}/storage/app/tmp"
    chown -R "${LUMO_USER}:${LUMO_GROUP}" "${INSTALL_DIR}/storage/app/tmp"

    log_success "Panel files installed to ${INSTALL_DIR}"
}

# =============================================================================
# Dependencies
# =============================================================================

install_panel_dependencies() {
    log_step "Installing Panel dependencies"

    cd "$INSTALL_DIR"

    # Install Composer dependencies
    if [[ -f "composer.json" ]]; then
        log_info "Installing PHP dependencies..."

        if [[ -f "composer.lock" ]]; then
            sudo -u "$LUMO_USER" composer install --no-dev --optimize-autoloader --no-interaction 2>&1 || {
                log_warning "Composer install failed, trying with --ignore-platform-reqs"
                sudo -u "$LUMO_USER" composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs
            }
        else
            sudo -u "$LUMO_USER" composer update --no-dev --optimize-autoloader --no-interaction 2>&1 || true
        fi
    fi

    # Install NPM dependencies
    if [[ -f "package.json" ]]; then
        log_info "Installing Node.js dependencies..."

        if [[ -f "package-lock.json" ]]; then
            sudo -u "$LUMO_USER" npm ci --no-audit 2>&1 || {
                log_warning "npm ci failed, trying npm install"
                sudo -u "$LUMO_USER" npm install --no-audit
            }
        else
            sudo -u "$LUMO_USER" npm install --no-audit 2>&1 || true
        fi

        if [[ -f "vite.config.js" ]] || [[ -f "vite.config.ts" ]]; then
            log_info "Building frontend assets..."
            sudo -u "$LUMO_USER" npm run build 2>&1 || log_warning "Frontend build failed"
        fi
    fi

    log_success "Dependencies installed"
}

# =============================================================================
# Configuration
# =============================================================================

configure_panel() {
    log_step "Configuring Lumo Panel"

    cd "$INSTALL_DIR"

    # Generate application key
    local app_key
    app_key=$(php -r "echo 'base64:' . base64_encode(random_bytes(32));")

    # Generate server ID
    local server_id
    server_id=$(cat /proc/sys/kernel/random/uuid)

    # Create .env file
    cat > "$INSTALL_DIR/.env" << EOF
# Lumo Panel Configuration
# Generated by install script on $(date -Iseconds)

# Application
APP_NAME=Lumo
APP_ENV=production
APP_KEY=${app_key}
APP_DEBUG=false
APP_URL=https://${DOMAIN}
APP_TIMEZONE=UTC
APP_LOCALE=en

# Server Identity
LOCAL_SERVER_ID=${server_id}

# Database
DB_CONNECTION=${DB_CONNECTION}
EOF

    # Add database-specific configuration
    case "$DB_CONNECTION" in
        mysql)
            cat >> "$INSTALL_DIR/.env" << EOF
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
EOF
            ;;
        pgsql)
            cat >> "$INSTALL_DIR/.env" << EOF
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
EOF
            ;;
        sqlite)
            cat >> "$INSTALL_DIR/.env" << EOF
DB_DATABASE=${INSTALL_DIR}/database/database.sqlite
EOF
            ;;
    esac

    cat >> "$INSTALL_DIR/.env" << EOF

# Session & Cache
SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=true
SESSION_SECURE_COOKIE=true
CACHE_STORE=database

# Queue (Redis for Horizon)
QUEUE_CONNECTION=redis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

# Daemon Configuration
DAEMON_SOCKET_PATH=${DAEMON_SOCKET_PATH}
DAEMON_SECRET=${DAEMON_SECRET}
DAEMON_TIMEOUT=30

# Mail
MAIL_MAILER=log
MAIL_FROM_ADDRESS=noreply@${DOMAIN}
MAIL_FROM_NAME="\${APP_NAME}"

# Logging
LOG_CHANNEL=stack
LOG_LEVEL=warning
EOF

    chown "${LUMO_USER}:${LUMO_GROUP}" "$INSTALL_DIR/.env"
    chmod 600 "$INSTALL_DIR/.env"

    log_success "Panel .env configured"
}

# =============================================================================
# Database Setup
# =============================================================================

setup_database() {
    log_step "Setting up database"

    case "$DB_CONNECTION" in
        mysql)
            log_info "Creating MySQL database and user..."
            wait_for_service "mysqladmin ping" 30

            local mysql_success=false

            # Try daemon first
            if [[ "$USE_DAEMON" == "true" ]]; then
                if daemon_create_database "$DB_NAME" "mysql" && \
                   daemon_create_db_user "$DB_USER" "$DB_PASSWORD" "$DB_NAME" "mysql"; then
                    mysql_success=true
                    log_success "MySQL database created via daemon"
                else
                    log_warning "Daemon database creation failed, falling back to direct MySQL"
                fi
            fi

            # Fallback to direct MySQL
            if [[ "$mysql_success" != "true" ]]; then
                mysql -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" || die "Failed to create MySQL database"
                mysql -e "CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASSWORD}';" || die "Failed to create MySQL user"
                mysql -e "GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';" || die "Failed to grant MySQL privileges"
                mysql -e "FLUSH PRIVILEGES;" || die "Failed to flush MySQL privileges"
                log_success "MySQL database created"
            fi
            ;;
        pgsql)
            log_info "Creating PostgreSQL database and user..."
            wait_for_service "sudo -u postgres pg_isready" 30

            local pgsql_success=false

            # Try daemon first
            if [[ "$USE_DAEMON" == "true" ]]; then
                if daemon_create_database "$DB_NAME" "pgsql" && \
                   daemon_create_db_user "$DB_USER" "$DB_PASSWORD" "$DB_NAME" "pgsql"; then
                    pgsql_success=true
                    log_success "PostgreSQL database created via daemon"
                else
                    log_warning "Daemon database creation failed, falling back to direct PostgreSQL"
                fi
            fi

            # Fallback to direct PostgreSQL
            if [[ "$pgsql_success" != "true" ]]; then
                # Check if user already exists before creating
                if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1; then
                    sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH ENCRYPTED PASSWORD '${DB_PASSWORD}';" || die "Failed to create PostgreSQL user"
                fi

                # Check if database already exists before creating
                if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
                    sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};" || die "Failed to create PostgreSQL database"
                fi

                sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};" || die "Failed to grant PostgreSQL privileges"
                log_success "PostgreSQL database created"
            fi
            ;;
        sqlite)
            log_info "Creating SQLite database..."

            if [[ "$USE_DAEMON" == "true" ]]; then
                daemon_mkdir "$INSTALL_DIR/database" "$LUMO_USER" "$LUMO_GROUP" "0755" || mkdir -p "$INSTALL_DIR/database"
            else
                mkdir -p "$INSTALL_DIR/database"
            fi

            touch "$INSTALL_DIR/database/database.sqlite"
            chown "${LUMO_USER}:${LUMO_GROUP}" "$INSTALL_DIR/database"
            chown "${LUMO_USER}:${LUMO_GROUP}" "$INSTALL_DIR/database/database.sqlite"
            chmod 664 "$INSTALL_DIR/database/database.sqlite"
            log_success "SQLite database created"
            ;;
    esac
}

# =============================================================================
# Migrations
# =============================================================================

run_migrations() {
    log_step "Running database migrations"

    cd "$INSTALL_DIR"

    if [[ -f "artisan" ]]; then
        sudo -u "$LUMO_USER" php artisan migrate --force || log_warning "Migrations failed"
        sudo -u "$LUMO_USER" php artisan db:seed --force 2>/dev/null || true
        log_success "Migrations completed"
    else
        log_warning "artisan file not found, skipping migrations"
    fi
}

# =============================================================================
# Optimization
# =============================================================================

optimize_panel() {
    log_step "Optimizing Panel for production"

    cd "$INSTALL_DIR"

    if [[ -f "artisan" ]]; then
        sudo -u "$LUMO_USER" php artisan config:cache 2>/dev/null || true
        sudo -u "$LUMO_USER" php artisan route:cache 2>/dev/null || true
        sudo -u "$LUMO_USER" php artisan view:cache 2>/dev/null || true
        sudo -u "$LUMO_USER" php artisan icons:cache 2>/dev/null || true
        log_success "Panel optimized"
    fi
}
